// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_net_web_app.Data;

#nullable disable

namespace asp_net_web_app.Migrations
{
    [DbContext(typeof(DatabaseWrapper))]
    partial class DatabaseWrapperModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("asp_net_web_app.Data.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("paidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("paymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("stripeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("paymentId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("asp_net_web_app.Data.Pricing", b =>
                {
                    b.Property<int>("pricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("baseNightlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("cancellationFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("earlyCheckInFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("largeSiteMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("lateCheckOutFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("seasonMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("specialEventMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("utilityMultiplier")
                        .HasColumnType("TEXT");

                    b.HasKey("pricingId");

                    b.ToTable("Pricing", (string)null);
                });

            modelBuilder.Entity("asp_net_web_app.Data.Reservation", b =>
                {
                    b.Property<int>("reservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isEligible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("totalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("reservationId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("asp_net_web_app.Data.Site", b =>
                {
                    b.Property<int>("siteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<double>("length")
                        .HasColumnType("REAL");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("width")
                        .HasColumnType("REAL");

                    b.HasKey("siteId");

                    b.ToTable("Sites", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Site");

                    b.UseTphMappingStrategy();
            modelBuilder.Entity("asp_net_web_app.Data.DbSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("asp_net_web_app.Data.DbSitePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DbSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DbSiteId");

                    b.ToTable("SitePhotos", (string)null);
                });

            modelBuilder.Entity("asp_net_web_app.Data.DbSitePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("DbSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DbSiteId");

                    b.ToTable("SitePrices", (string)null);
                });

            modelBuilder.Entity("asp_net_web_app.Data.Employee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("employeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("asp_net_web_app.Data.Reservations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("asp_net_web_app.Data.Users", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("middleInitial")
                        .HasColumnType("TEXT");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("streetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Users");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("asp_net_web_app.Data.Lot", b =>
                {
                    b.HasBaseType("asp_net_web_app.Data.Site");

                    b.Property<string>("utilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Lot");
                });

            modelBuilder.Entity("asp_net_web_app.Data.StorageContainer", b =>
                {
                    b.HasBaseType("asp_net_web_app.Data.Site");

                    b.Property<double>("height")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("StorageContainer");
                });

            modelBuilder.Entity("asp_net_web_app.Data.Customer", b =>
                {
                    b.HasBaseType("asp_net_web_app.Data.Users");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("asp_net_web_app.Data.Staff", b =>
                {
                    b.HasBaseType("asp_net_web_app.Data.Users");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCurrentEmployee")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Staff");
                });

            modelBuilder.Entity("asp_net_web_app.Data.Admin", b =>
                {
                    b.HasBaseType("asp_net_web_app.Data.Staff");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("asp_net_web_app.Data.DbSitePhoto", b =>
                {
                    b.HasOne("asp_net_web_app.Data.DbSite", null)
                        .WithMany("Photos")
                        .HasForeignKey("DbSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("asp_net_web_app.Data.DbSitePrice", b =>
                {
                    b.HasOne("asp_net_web_app.Data.DbSite", null)
                        .WithMany("PriceRules")
                        .HasForeignKey("DbSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("asp_net_web_app.Data.DbSite", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("PriceRules");
                });
#pragma warning restore 612, 618
        }
    }
}
